export const APP_ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  DAY_ALREADY_EXISTS: "DAY_ALREADY_EXISTS",
  DAY_NOT_FOUND: "DAY_NOT_FOUND",
  FAILED_TO_LOAD_DAY: "FAILED_TO_LOAD_DAY",
  FAILED_TO_CREATE_DAY: "FAILED_TO_CREATE_DAY",
  FAILED_TO_UPDATE_DAY: "FAILED_TO_UPDATE_DAY",
  FAILED_TO_DELETE_DAY: "FAILED_TO_DELETE_DAY",
} as const;

export type AppErrorCode =
  (typeof APP_ERROR_CODES)[keyof typeof APP_ERROR_CODES];
